---
title: "&#39; Throw &#39; l’instruction ne peut pas omettre l’opérande en dehors un &#39; Catch &#39; instruction ou à l’intérieur un &#39; Enfin &#39; instruction"
ms.date: 07/20/2015
ms.prod: .net
ms.technology: devlang-visual-basic
ms.topic: article
f1_keywords:
- vbc30666
- bc30666
helpviewer_keywords: BC30666
ms.assetid: a208a6ea-0e36-4bf1-8984-4de1a0e38a2a
caps.latest.revision: "8"
author: dotnet-bot
ms.author: dotnetcontent
ms.openlocfilehash: 5fa3be0ca47a4158b3abeef9801148e3f19d3b36
ms.sourcegitcommit: c0dd436f6f8f44dc80dc43b07f6841a00b74b23f
ms.translationtype: MT
ms.contentlocale: fr-FR
ms.lasthandoff: 01/19/2018
---
# <a name="39throw39-statement-cannot-omit-operand-outside-a-39catch39-statement-or-inside-a-39finally39-statement"></a>&#39; Throw &#39; l’instruction ne peut pas omettre l’opérande en dehors un &#39; Catch &#39; instruction ou à l’intérieur un &#39; Enfin &#39; instruction
Les instructions`Throw` situées en dehors de l’instruction `Catch` doivent fournir le nom d’un objet exception.  
  
 **ID d’erreur :** BC30666  
  
## <a name="to-correct-this-error"></a>Pour corriger cette erreur  
  
1.  Spécifiez le nom d’un objet d’exception dérivé de `System.Exception`.  
  
2.  Restructurez votre code pour que l’instruction `Throw` se trouve dans un bloc `Catch` .  
  
## <a name="see-also"></a>Voir aussi  
 [Throw (instruction)](../../visual-basic/language-reference/statements/throw-statement.md)  
 [Try...Catch...Finally (instruction)](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)  
 [Classe d’exception dans Visual Basic](http://msdn.microsoft.com/library/9aac396f-34ca-4afb-8e6c-e523cb690ba9)  
 [Exceptions et gestion des erreurs dans Visual Basic](http://msdn.microsoft.com/library/3e351e73-cf23-40ab-8b60-05794160529e)
